name: Sync Publishing Secrets
on: [workflow_dispatch]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^(MODRINTH|CURSEFORGE|MAVEN|CLASSIC_GITHUB)_TOKEN$
          REPOSITORIES: |
            mineblock11/example-repo
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CLASSIC_GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
