name: Sync Publishing Secrets
on: [workflow_dispatch, push]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.10.0
        with:
          SECRETS: |
            ^(MODRINTH|CURSEFORGE|MAVEN|CLASSIC_GITHUB)_TOKEN$
          REPOSITORIES: |
            IMB11/Fog
            IMB11/Woof
            IMB11/Spoticraft
            IMB11/Armorful
            IMB11/MRU
            IMB11/ExtraShields
            IMB11/SnowUnderTrees
            IMB11/terravista
            IMB11/ToggleMyTooltips
            IMB11/Spoofer
            IMB11/QuickplayBackport
            IMB11/SimpleBroadcast
            IMB11/BackBlur
            IMB11/continue-button
            IMB11/SkinShuffle
            IMB11/Sounds
            IMB11/Flow
            IMB11/Fog
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CLASSIC_GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
