name: Sync Publishing Secrets
on: [workflow_dispatch, push]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^(MODRINTH|CURSEFORGE|MAVEN|CLASSIC_GITHUB)_TOKEN$
          REPOSITORIES: |
            mineblock11/FogLooksGoodNow
            mineblock11/Woof
            mineblock11/Spoticraft
            mineblock11/Armorful
            mineblock11/MRU
            mineblock11/SnowUnderTrees
            mineblock11/terravista
            mineblock11/ToggleMyTooltips
            mineblock11/Spoofer
            mineblock11/QuickplayBackport
            mineblock11/SimpleBroadcast
            mineblock11/BackBlur
            mineblock11/continue-button
            mineblock11/SkinShuffle
            mineblock11/Sonance
          REPOSITORIES_LIST_REGEX: false
          GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CLASSIC_GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
